"""added profile pic

Revision ID: 404da664ce24
Revises: fb429597c4fc
Create Date: 2022-09-23 17:04:56.734906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404da664ce24'
down_revision = 'fb429597c4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
